version: 2
jobs:
  build:
    docker:
      - image: cimg/android:2022.09.1
    steps:
      - checkout
      - run:
          name: Install python
          command: sudo apt-get update && sudo apt-get install -y python3 python3-virtualenv shellcheck wamerican
      - run:
          name: Shellcheck
          command: find . -name '*.sh' | xargs shellcheck
      - run:
          name: Set up virtualenv
          command: virtualenv -p python3 venv
      - run:
          name: Download python dependencies
          command: venv/bin/pip install -U -r requirements.txt
      - run:
          name: Run python static checks and unit tests
          command: source venv/bin/activate && ./test_python.sh
      - run:
          name: Fetch inflections
          command: db/download_inflections.sh
      - run:
          name: Build test database
          command: source venv/bin/activate && DICT_LIMIT_LINES=1000 ./db/build_dict_db.sh
      - run:
          name: Download Android dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Build Android app
          command: ./gradlew build
      - run:
          name: Maybe run emulator tests
          command: if [ "$CIRCLE_BRANCH" = master ] ; then ./emulator_tests.sh ; else echo "Not on master, not running emulator tests." ; fi
