version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-29
    steps:
      - checkout
      - run:
          name: Install python
          command: sudo apt-get update && sudo apt-get install -y python3 python3-virtualenv
      - run:
          name: Set up virtualenv
          command: python3 /usr/lib/python3/dist-packages/virtualenv.py -p python3 venv
      - run:
          name: Download python dependencies
          command: venv/bin/pip install -U -r db/requirements.txt
      - run:
          name: Run python static checks and unit tests
          command: source venv/bin/activate && ./db/test.sh
      - run:
          name: Smoke-test parse_scanned_by.py
          command: source venv/bin/activate && bzip2 -ckd db/oe_bosworthtoller.txt.bz2 | db/parse_scanned_bt.py > /dev/null
